// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtW8jvzykVBd4q2FVtWI2qYyUR73qUKT8',
    appId: '1:51190346557:web:18a5a93d75e194a6690b54',
    messagingSenderId: '51190346557',
    projectId: 'flutter-chat-app-8abb8',
    authDomain: 'flutter-chat-app-8abb8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8abb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYhtX_lrIXrdZovzfMg0FZ3omTFOJ3BWc',
    appId: '1:51190346557:android:f867fe9dec5382f7690b54',
    messagingSenderId: '51190346557',
    projectId: 'flutter-chat-app-8abb8',
    storageBucket: 'flutter-chat-app-8abb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUftjrLoMd5slTYIsRkSbUYlhhaFaUQzs',
    appId: '1:51190346557:ios:c1be2ca1a2e05613690b54',
    messagingSenderId: '51190346557',
    projectId: 'flutter-chat-app-8abb8',
    storageBucket: 'flutter-chat-app-8abb8.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUftjrLoMd5slTYIsRkSbUYlhhaFaUQzs',
    appId: '1:51190346557:ios:c1be2ca1a2e05613690b54',
    messagingSenderId: '51190346557',
    projectId: 'flutter-chat-app-8abb8',
    storageBucket: 'flutter-chat-app-8abb8.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtW8jvzykVBd4q2FVtWI2qYyUR73qUKT8',
    appId: '1:51190346557:web:e06da3d03249f598690b54',
    messagingSenderId: '51190346557',
    projectId: 'flutter-chat-app-8abb8',
    authDomain: 'flutter-chat-app-8abb8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8abb8.appspot.com',
  );
}
